"""create remaining tables

Revision ID: 04a7e0377c9b
Revises: 63a953d39166
Create Date: 2025-12-19 10:57:13.503312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '04a7e0377c9b'
down_revision: Union[str, Sequence[str], None] = '63a953d39166'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'billing_accounts',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
        sa.Column('stripe_subscription_id',
                  sa.String(length=255), nullable=True),

        # ★DB側defaultを付与（任意の修正）
        sa.Column('subscription_status', sa.String(length=32),
                  nullable=False, server_default=sa.text("'NONE'")),
        sa.Column('current_plan', sa.String(length=16),
                  nullable=False, server_default=sa.text("'free'")),

        sa.Column('updated_at', sa.DateTime(timezone=True),
                  server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', name='uq_billing_account_user_id')
    )
    op.create_index(op.f('ix_billing_accounts_stripe_customer_id'),
                    'billing_accounts', ['stripe_customer_id'], unique=False)
    op.create_index(op.f('ix_billing_accounts_stripe_subscription_id'),
                    'billing_accounts', ['stripe_subscription_id'], unique=False)

    op.create_table(
        'daily_nutrition_reports',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('date', sa.Date(), nullable=False),
        sa.Column('summary', sa.Text(), nullable=False),
        sa.Column('good_points', postgresql.ARRAY(sa.Text()),
                  server_default='{}', nullable=False),
        sa.Column('improvement_points', postgresql.ARRAY(
            sa.Text()), server_default='{}', nullable=False),
        sa.Column('tomorrow_focus', postgresql.ARRAY(
            sa.Text()), server_default='{}', nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True),
                  server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'date',
                            name='uq_daily_nutrition_reports_user_id_date')
    )
    op.create_index(op.f('ix_daily_nutrition_reports_date'),
                    'daily_nutrition_reports', ['date'], unique=False)
    op.create_index(op.f('ix_daily_nutrition_reports_user_id'),
                    'daily_nutrition_reports', ['user_id'], unique=False)

    op.create_table(
        'daily_nutrition_summaries',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('date', sa.Date(), nullable=False),
        sa.Column('generated_at', sa.DateTime(timezone=True),
                  server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True),
                  server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'date',
                            name='uq_daily_nutrition_user_date')
    )
    op.create_index(op.f('ix_daily_nutrition_summaries_date'),
                    'daily_nutrition_summaries', ['date'], unique=False)
    op.create_index(op.f('ix_daily_nutrition_summaries_user_id'),
                    'daily_nutrition_summaries', ['user_id'], unique=False)

    op.create_table(
        'food_entries',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('date', sa.Date(), nullable=False),
        sa.Column('meal_type', sa.String(length=16), nullable=False),
        sa.Column('meal_index', sa.SmallInteger(), nullable=True),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('amount_value', sa.Float(), nullable=True),
        sa.Column('amount_unit', sa.String(length=32), nullable=True),
        sa.Column('serving_count', sa.Float(), nullable=True),
        sa.Column('note', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True),
                  server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True),
                  server_default=sa.text('now()'), nullable=False),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_entries_date'),
                    'food_entries', ['date'], unique=False)
    op.create_index(op.f('ix_food_entries_deleted_at'),
                    'food_entries', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_food_entries_meal_type'),
                    'food_entries', ['meal_type'], unique=False)
    op.create_index(op.f('ix_food_entries_user_id'),
                    'food_entries', ['user_id'], unique=False)

    op.create_table(
        'meal_nutrition_summaries',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('date', sa.Date(), nullable=False),
        sa.Column('meal_type', sa.String(length=16), nullable=False),
        sa.Column('meal_index', sa.SmallInteger(), nullable=True),
        sa.Column('generated_at', sa.DateTime(timezone=True),
                  server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True),
                  server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'date', 'meal_type',
                            'meal_index', name='uq_meal_nutrition_user_date_slot')
    )
    op.create_index(op.f('ix_meal_nutrition_summaries_date'),
                    'meal_nutrition_summaries', ['date'], unique=False)
    op.create_index(op.f('ix_meal_nutrition_summaries_meal_type'),
                    'meal_nutrition_summaries', ['meal_type'], unique=False)
    op.create_index(op.f('ix_meal_nutrition_summaries_user_id'),
                    'meal_nutrition_summaries', ['user_id'], unique=False)

    # ★注意点2の修正：meal_index が NULL の行は (user_id, date, meal_type) でユニークにする
    op.create_index(
        'uq_meal_nutrition_summaries_user_date_type_null',
        'meal_nutrition_summaries',
        ['user_id', 'date', 'meal_type'],
        unique=True,
        postgresql_where=sa.text('meal_index IS NULL'),
    )

    op.create_table(
        'meal_recommendations',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('generated_for_date', sa.Date(), nullable=False),
        sa.Column('body', sa.Text(), nullable=False),

        # ★DB側defaultを付与（任意の修正）
        sa.Column('tips', postgresql.ARRAY(sa.Text()),
                  server_default='{}', nullable=False),

        sa.Column('created_at', sa.DateTime(timezone=True),
                  server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'generated_for_date',
                            name='uq_meal_recommendation_user_date')
    )
    op.create_index(op.f('ix_meal_recommendations_generated_for_date'),
                    'meal_recommendations', ['generated_for_date'], unique=False)
    op.create_index(op.f('ix_meal_recommendations_user_id'),
                    'meal_recommendations', ['user_id'], unique=False)

    op.create_table(
        'targets',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('goal_type', sa.String(length=50), nullable=False),
        sa.Column('goal_description', sa.Text(), nullable=True),
        sa.Column('activity_level', sa.String(length=50), nullable=False),

        # ★DB側defaultを付与（任意の修正）
        sa.Column('is_active', sa.Boolean(), nullable=False,
                  server_default=sa.text('false')),

        sa.Column('llm_rationale', sa.Text(), nullable=True),
        sa.Column('disclaimer', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_targets_is_active'),
                    'targets', ['is_active'], unique=False)
    op.create_index(op.f('ix_targets_user_id'),
                    'targets', ['user_id'], unique=False)

    op.create_table(
        'daily_nutrition_nutrients',
        sa.Column('summary_id', sa.UUID(), nullable=False),
        sa.Column('code', sa.String(length=50), nullable=False),
        sa.Column('amount_value', sa.Float(), nullable=False),
        sa.Column('amount_unit', sa.String(length=20), nullable=False),
        sa.Column('source', sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ['summary_id'], ['daily_nutrition_summaries.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('summary_id', 'code')
    )

    op.create_table(
        'daily_target_snapshots',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('date', sa.Date(), nullable=False),
        sa.Column('target_id', sa.UUID(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ['target_id'], ['targets.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'date',
                            name='uq_daily_target_snapshot_user_date')
    )
    op.create_index(op.f('ix_daily_target_snapshots_date'),
                    'daily_target_snapshots', ['date'], unique=False)
    op.create_index(op.f('ix_daily_target_snapshots_user_id'),
                    'daily_target_snapshots', ['user_id'], unique=False)

    op.create_table(
        'meal_nutrition_nutrients',
        sa.Column('summary_id', sa.UUID(), nullable=False),
        sa.Column('code', sa.String(length=50), nullable=False),
        sa.Column('amount_value', sa.Float(), nullable=False),
        sa.Column('amount_unit', sa.String(length=20), nullable=False),
        sa.Column('source', sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ['summary_id'], ['meal_nutrition_summaries.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('summary_id', 'code')
    )

    op.create_table(
        'target_nutrients',
        sa.Column('target_id', sa.UUID(), nullable=False),
        sa.Column('code', sa.String(length=50), nullable=False),
        sa.Column('amount_value', sa.Float(), nullable=False),
        sa.Column('amount_unit', sa.String(length=20), nullable=False),
        sa.Column('source', sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(
            ['target_id'], ['targets.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('target_id', 'code')
    )

    op.create_table(
        'daily_target_snapshot_nutrients',
        sa.Column('snapshot_id', sa.UUID(), nullable=False),
        sa.Column('code', sa.String(length=50), nullable=False),
        sa.Column('amount_value', sa.Float(), nullable=False),
        sa.Column('amount_unit', sa.String(length=20), nullable=False),
        sa.Column('source', sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(
            ['snapshot_id'], ['daily_target_snapshots.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('snapshot_id', 'code')
    )

    op.add_column('profiles', sa.Column(
        'meals_per_day', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'meals_per_day')
    op.drop_table('daily_target_snapshot_nutrients')
    op.drop_table('target_nutrients')
    op.drop_table('meal_nutrition_nutrients')
    op.drop_index(op.f('ix_daily_target_snapshots_user_id'),
                  table_name='daily_target_snapshots')
    op.drop_index(op.f('ix_daily_target_snapshots_date'),
                  table_name='daily_target_snapshots')
    op.drop_table('daily_target_snapshots')
    op.drop_table('daily_nutrition_nutrients')
    op.drop_index(op.f('ix_targets_user_id'), table_name='targets')
    op.drop_index(op.f('ix_targets_is_active'), table_name='targets')
    op.drop_table('targets')
    op.drop_index(op.f('ix_meal_recommendations_user_id'),
                  table_name='meal_recommendations')
    op.drop_index(op.f('ix_meal_recommendations_generated_for_date'),
                  table_name='meal_recommendations')
    op.drop_table('meal_recommendations')

    # ★注意点2の修正で追加した partial unique index を落とす
    op.drop_index('uq_meal_nutrition_summaries_user_date_type_null',
                  table_name='meal_nutrition_summaries')

    op.drop_index(op.f('ix_meal_nutrition_summaries_user_id'),
                  table_name='meal_nutrition_summaries')
    op.drop_index(op.f('ix_meal_nutrition_summaries_meal_type'),
                  table_name='meal_nutrition_summaries')
    op.drop_index(op.f('ix_meal_nutrition_summaries_date'),
                  table_name='meal_nutrition_summaries')
    op.drop_table('meal_nutrition_summaries')
    op.drop_index(op.f('ix_food_entries_user_id'), table_name='food_entries')
    op.drop_index(op.f('ix_food_entries_meal_type'), table_name='food_entries')
    op.drop_index(op.f('ix_food_entries_deleted_at'),
                  table_name='food_entries')
    op.drop_index(op.f('ix_food_entries_date'), table_name='food_entries')
    op.drop_table('food_entries')
    op.drop_index(op.f('ix_daily_nutrition_summaries_user_id'),
                  table_name='daily_nutrition_summaries')
    op.drop_index(op.f('ix_daily_nutrition_summaries_date'),
                  table_name='daily_nutrition_summaries')
    op.drop_table('daily_nutrition_summaries')
    op.drop_index(op.f('ix_daily_nutrition_reports_user_id'),
                  table_name='daily_nutrition_reports')
    op.drop_index(op.f('ix_daily_nutrition_reports_date'),
                  table_name='daily_nutrition_reports')
    op.drop_table('daily_nutrition_reports')
    op.drop_index(op.f('ix_billing_accounts_stripe_subscription_id'),
                  table_name='billing_accounts')
    op.drop_index(op.f('ix_billing_accounts_stripe_customer_id'),
                  table_name='billing_accounts')
    op.drop_table('billing_accounts')
    # ### end Alembic commands ###
