"""add tutorial completions table v2

Revision ID: 6c70d87cac2b
Revises: f9c3fd58b44a
Create Date: 2026-02-01 17:25:58.226085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c70d87cac2b'
down_revision: Union[str, Sequence[str], None] = 'f9c3fd58b44a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tutorial_completions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tutorial_id', sa.String(length=50), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'tutorial_id')
    )
    op.create_index('ix_tutorial_completions_user_id', 'tutorial_completions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tutorial_completions_user_id', table_name='tutorial_completions')
    op.drop_table('tutorial_completions')
    # ### end Alembic commands ###
