"""Add created_at and updated_at to tutorial_completions

Revision ID: 736c5c90d610
Revises: 6c70d87cac2b
Create Date: 2026-02-01 17:41:14.708098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '736c5c90d610'
down_revision: Union[str, Sequence[str], None] = '6c70d87cac2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tutorial_completions', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('tutorial_completions', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tutorial_completions', 'updated_at')
    op.drop_column('tutorial_completions', 'created_at')
    # ### end Alembic commands ###
